import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import ConvexClientProvider from "./ConvexClientProvider";
import { Toaster } from "sonner";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "WEB_GENERATOR",
  description: "Generated by create next app",
};

/**
 * Root layout component that wraps all pages with Convex, auth, theme,
 * and toast notification providers.
 * @param {{ children: React.ReactNode }} props - Component props.
 * @returns {JSX.Element} The root HTML structure with all providers.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ConvexClientProvider>
          <Provider>
            {children}
            <Toaster />
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
